name: GitHub Actions Experiment
on: [push]
jobs:
  Virtual-Machine:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
      - name: Create virtual machine
        run: vagrant up
