name: GitHub Actions Experiment
on: [push]
jobs:
  Virtual-Machine:
    runs-on: ubuntu-latest
    steps:
      - run: lsb_release -a
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: git ls-files
      - run: ls -lah Assistive-Webdriver
