name: GitHub Actions Experiment
on: [push]
jobs:
  Virtual-Machine:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install ARIA-AT dependencies
        run: npm install
        working-directory: aria-at
      - name: Build ARIA-AT tests
        run: npm run build
        working-directory: aria-at
      - name: Install aria-at-automation-harness
        run: npm install
        working-directory: aria-at-automation-harness
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
      - name: Create directory for virtual machines
        run: mkdir "$HOME/VirtualBox VMs"
        shell: bash
      # This step cannot utilize the cache provided by GitHub Actions because
      # the size on disk (about 40 GB) exceeds the maximum available for
      # caching (10 GB)
      - name: Download archive of VirtualBox machine image
        run: cd "$HOME/VirtualBox VMs" && wget --no-verbose --show-progress --progress=dot:giga https://ewr1.vultrobjects.com/boxes/macos-1015.tar
        shell: bash
      - name: Extract VirtualBox machine image
        run: cd "$HOME/VirtualBox VMs" && tar xvf macos-1015.tar
        shell: bash
      - name: Register VirtualBox machine image
        run: VBoxManage registervm "$HOME/VirtualBox VMs/macos-1015/macos-1015.vbox"
        shell: bash
      - name: Collect results
        run: ./collect.sh
        env:
          AWD_BROWSER_NAME: firefox
          AWD_VM_NAME: macos-1015
          AWD_SNAPSHOT_NAME: Base
