name: GitHub Actions Experiment
on: [push]
jobs:
  Virtual-Machine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch DLLs
        run: ./fetch-dlls.sh
