name: GitHub Actions Experiment
on: [push]
jobs:
  Virtual-Machine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch DLLs
        run: ./fetch-dlls.sh
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install VirtualBox
        run: sudo apt-get install --yes virtualbox-6.1
