name: GitHub Actions Experiment
on: [push]
jobs:
  Virtual-Machine:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch VirtualBox
        run:
          wget
            --output-document virtualbox-6.1.deb
            'https://download.virtualbox.org/virtualbox/6.1.32/virtualbox-6.1_6.1.32-149290~Ubuntu~eoan_amd64.deb'
      - name: Install VirtualBox
        run: sudo dpkg -i virtualbox-6.1.deb
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch DLLs
        run: ./fetch-dlls.sh
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install pnpm
        run: npm install -g pnpm
